"""empty message

Revision ID: 32cc9cce92a4
Revises: 071a69751a28
Create Date: 2018-12-15 22:24:05.828093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cc9cce92a4'
down_revision = '071a69751a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_dates', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_dates', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_dates', type_='foreignkey')
    op.drop_column('event_dates', 'event_id')
    # ### end Alembic commands ###
