"""empty message

Revision ID: be334120354e
Revises: 5c11d02d1b86
Create Date: 2018-12-15 21:35:37.433749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be334120354e'
down_revision = '5c11d02d1b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'finish_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('finish_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
